### ISSUE TITLE
Loops And Blocks

### ISSUE THREAD

**Issue by boopdoop** [liamgens/BuckNaked#18]
As a developer, I'd like to be able to implement loops that repeat code ran within the BVM. I would also like to have if else statements. I would like the control of these types of statements to be determined using conditional statements.

**Comment by bmmcmahon** [comment]
# Loops and Blocks Acceptance Tests
## Simple while loop test
Type the code into the editor:
```
var x 0
var cond true
while cond
print x
add x 1 x
leq x 100 cond
end
```
Running this should print the numbers 0-100 in the output window.

## Complex nested if, else, and while loops test
Type the code into the editor:
```
var x 0
var cond true
while cond
  var isZero
  equals x 0 isZero
  if isZero
    print 1
  else
    var continue true
    var y 1
    var fact 1
    while continue
      mul y fact fact
      add 1 y y
      leq y x continue
    end
    print fact
  end
  add 1 x x
  leq x 6 cond
end
```
Running this should print out the result of the factorial function on inputs from 0-6:
```
1 
1 
2 
6 
24 
120 
720 
```
to the output window.
